import { z } from "zod";

export const mcpFormSchema = z.object({
  name: z.string().min(1),
  displayName: z.string(),
  transport: z.enum(["stdio", "sse", "streamable-http"]),
  command: z.string(),
  args: z.string(),
  url: z.string(),
  headers: z.record(z.string(), z.string()),
  env: z.record(z.string(), z.string()),
  toolPrefix: z.string(),
  timeout: z.number().min(1),
  enabled: z.boolean(),
  requireUserCreds: z.boolean(),
  preset: z.enum(["generic", "facebook"]),
  facebookPages: z.array(z.object({
    page_id: z.string(),
    name: z.string().optional(),
    access_token: z.string().optional(),
    watermark: z.object({
      enabled: z.boolean(),
      mode: z.enum(["logo", "text"]),
      text: z.string().optional(),
      logo_path: z.string().optional(),
      logo_url: z.string().optional(),
      logo_preview_url: z.string().optional(),
      x_pct: z.number(),
      y_pct: z.number(),
      scale_pct: z.number(),
      opacity: z.number(),
    }).optional(),
    watermarks: z.array(z.object({
      enabled: z.boolean(),
      mode: z.enum(["logo", "text"]),
      text: z.string().optional(),
      logo_path: z.string().optional(),
      logo_url: z.string().optional(),
      logo_preview_url: z.string().optional(),
      x_pct: z.number(),
      y_pct: z.number(),
      scale_pct: z.number(),
      opacity: z.number(),
    })).optional(),
    comment_schedule: z.object({
      enabled: z.boolean(),
      comment_count: z.number(),
      window_ms: z.number(),
      min_gap_ms: z.number(),
      random_order: z.boolean(),
    }).optional(),
  })),
});

export type MCPFormData = z.infer<typeof mcpFormSchema>;
