import { z } from "zod";

export const mcpFormSchema = z.object({
  name: z.string().min(1),
  displayName: z.string(),
  transport: z.enum(["stdio", "sse", "streamable-http"]),
  command: z.string(),
  args: z.string(),
  url: z.string(),
  headers: z.record(z.string(), z.string()),
  env: z.record(z.string(), z.string()),
  toolPrefix: z.string(),
  timeout: z.number().min(1),
  enabled: z.boolean(),
  requireUserCreds: z.boolean(),
  preset: z.enum(["generic", "facebook", "google_drive"]),
  facebookPages: z.array(z.object({
    page_id: z.string(),
    name: z.string().optional(),
    access_token: z.string().optional(),
    watermark: z.object({
      enabled: z.boolean(),
      mode: z.enum(["logo", "text"]),
      text: z.string().optional(),
      logo_path: z.string().optional(),
      logo_url: z.string().optional(),
      logo_preview_url: z.string().optional(),
      x_pct: z.number(),
      y_pct: z.number(),
      scale_pct: z.number(),
      opacity: z.number(),
    }).optional(),
    watermarks: z.array(z.object({
      enabled: z.boolean(),
      mode: z.enum(["logo", "text"]),
      text: z.string().optional(),
      logo_path: z.string().optional(),
      logo_url: z.string().optional(),
      logo_preview_url: z.string().optional(),
      x_pct: z.number(),
      y_pct: z.number(),
      scale_pct: z.number(),
      opacity: z.number(),
    })).optional(),
    comment_schedule: z.object({
      enabled: z.boolean(),
      comment_count: z.number(),
      window_ms: z.number(),
      min_gap_ms: z.number(),
      random_order: z.boolean(),
    }).optional(),
  })),
  googleDrive: z.object({
    client_id: z.string(),
    client_secret: z.string(),
    refresh_token: z.string(),
    root_folder_id: z.string(),
    root_folder_name: z.string().optional(),
    cache_dir: z.string().optional(),
    cache_ttl_seconds: z.number().min(1),
    max_assets: z.number().min(1),
    agent_folder_grants: z.string().optional(),
    allow_public_link_import: z.boolean(),
    sync_time: z.string(),
    timezone: z.string(),
    visual_index_enabled: z.boolean(),
    visual_index_provider: z.string().optional(),
    visual_index_model: z.string().optional(),
    visual_format_provider: z.string().optional(),
    visual_format_model: z.string().optional(),
    visual_index_concurrency: z.number().min(1),
    visual_index_max_per_run: z.number().min(0),
    visual_index_time: z.string().optional(),
  }),
});

export type MCPFormData = z.infer<typeof mcpFormSchema>;
